apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  application.yml: |
    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://add695c197e0.kiszka-kis1.postgres.database.azure.com:5432/postgres
        username: psqladmin
        password: psqladmin

    security:
      jwt:
        secret-key: 173c7faaf30859adad7375b1b3dd8133ea35c673645d0b33b3b301e7bc5283ba
        expiration-time: 3600000